### ISSUE TITLE
Some toughs about the meeting18-04-2023 with Harena

### ISSUE THREAD

**Issue by niksonleonard** [niksonleonard/the-delightful-letters-mess-game#17]
Who played the game gave some interesting feedbacks:

* How to play the game?
* How many letter I got and many the Ladybug got?

Guilherme believes it is not a issue to expose the game but he was not sure about the fund rising.
Guess we should have a more consistent state of the fund page and the game development rodmap.
He suggested to put a QR code for the game inside the pack that they will distribute in the event. But We do not have time enough to publish the game in the Chanels.
He liked the idea of Harena be a partnership in the project and thinks is viable in the future the game be part of a way to rise fundings to the hospital.

**Comment by RaniB29** [comment]
I thing that this insue had to be closed
